### ISSUE TITLE
php sample always saying "Failed to take payment: "

### ISSUE THREAD

**Issue by kusumdas** [cardstream/cardstream-sample-code#1]
Hi,

I am trying to run php sample code, but it is always displaying message as "Failed to take payment".

Can you please give me any running sample?

regards
Kusum

**Comment by Quacky2200** [comment]
Hi Kusum,

What response message did you get from the failed payment error?

Regards,
Matthew

**Comment by kusumdas** [comment]
Hi,

I am getting below error in curl :

Curl error: SSL certificate problem: unable to get local issuer certificate

regards
Kusum

**Comment by kusumdas** [comment]
thanks for your time, its working fine by adding below line

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

regards

Kusum

**Comment by Quacky2200** [comment]
Hi Kusum,

Your CA certificates bundle is most likely outdated on your server and if you're using PHP < 5.6 you'll have to specify the certificate bundle manually. Setting peer verification to off is a security risk.

**Comment by kusumdas** [comment]
Thanks for your input, but I am very unknown with php as I am c# developer.

Actually I am integrating it using C#, but in the C#  response signature is
not getting matched so I tried the sample with php, whether it is working
fine with php or not.

I have tried using CSharp-Direct-Sample-master sample but in that I am
getting successful response ( responseCode=0) but my signature is not
getting matched.

I have to integrate it without 3D secure, I am attaching my c# sample code
here with which I have written using reference of
"CSharp-Direct-Sample-master".

Please help me if possible for you with C# or shall I post differently for
C#?

regards
Kusum

**Comment by Quacky2200** [comment]
I think it would be better if you could create a ticket by emailing us at solutions@cardstream.com or to create an issue in the [CSharp-Direct-Sample repository](https://github.com/cardstream/CSharp-Direct-Sample). 

The library may give you a response code of 1, this is due to a missing `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;` on line 251.

Otherwise Signatures may not match if the secret is malformed. Please make sure there aren't any spaces or other punctuation in the secret as it should only contain letters and numbers.

I also cannot see any attachments when you reply to GitHub messages by email. Either submit this to the above email or attach it directly in GitHub.

Regards,
Matthew

**Comment by kusumdas** [comment]
Thanks

**Comment by Quacky2200** [comment]
Hi @kusumdas,

Could you kindly tell me if this problem has been resolved and I'll close the ticket on GitHub for you.

Regards,
Matthew

**Comment by kusumdas** [comment]
yes, this is resolved, kindly close the ticket.
